#!/usr/bin/env php
<?php

	if (file_exists(__DIR__.'/../../autoload.php')) {
	    require __DIR__.'/../../autoload.php';
	} else {
	    require __DIR__.'/vendor/autoload.php';
	}

	use Symfony\Component\Console\Application;

	$application = new Application('Khan CLI', '1.0');

	$application->add(new Command\ServerCommand());
	$application->add(new Command\CreateCommand());
	$application->add(new Command\ControllerCommand());
	$application->add(new Command\HelperCommand());
	$application->add(new Command\GulpCommand());
	$application->add(new Command\SassCommand());
	$application->add(new Command\JsCommand());
	$application->add(new Command\MakeCommand());

	$application->run();
